version: '2'
services:
  vault:
    image: vault
    container_name: vault
    build:
      context: ./
      dockerfile: vault.dockerfile
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
      - ./volumes/plugins:/vault/plugins
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl


    # entrypoint: vault server -config=/vault/config/vault.hcl
# ENTRYPOINT [ "./test-entrypoint.sh" ]
